# Generated by Django 3.1.14 on 2022-04-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorytranslation',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='posttranslation',
            name='slug',
        ),
    ]
