version: '3.8'

services:
  web:
    build: .
    command: python /Django-Blog-Template/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/Django-Blog-Template
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - "DJANGO_SECRET_KEY=django-insecure-aujg0%%#*ecw14p2b5@%t=df!*(cq4wy+h*7k#%ai*ypwjj73u"
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
     - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: